-- MySQL Script generated by MySQL Workbench
-- Fri Oct 20 20:07:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_ricco
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_ricco` ;

-- -----------------------------------------------------
-- Schema bd_ricco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_ricco` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_ricco` ;

-- -----------------------------------------------------
-- Table `bd_ricco`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ricco`.`localidad` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_localidad` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_ricco`.`barrio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ricco`.`barrio` (
  `id_barrio` INT NOT NULL AUTO_INCREMENT,
  `nombre_barrio` VARCHAR(50) NULL DEFAULT NULL,
  `id_localidad` INT NOT NULL,
  PRIMARY KEY (`id_barrio`),
  CONSTRAINT `id_localidad`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `bd_ricco`.`localidad` (`id_localidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_localidad` ON `bd_ricco`.`barrio` (`id_localidad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd_ricco`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ricco`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_ricco`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ricco`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(50) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `clave_usuario` VARCHAR(50) NULL DEFAULT NULL,
  `telefono` INT NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `bd_ricco`.`rol` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_rol` ON `bd_ricco`.`usuario` (`id_rol` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd_ricco`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ricco`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  `precio_compra` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_ricco`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_usuario` ON `bd_ricco`.`compra` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd_ricco`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ricco`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(50) NULL DEFAULT NULL,
  `descripcion` VARCHAR(250) NULL DEFAULT NULL,
  `precio` DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bd_ricco`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ricco`.`detalle` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_compra` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_calculado` INT NOT NULL,
  PRIMARY KEY (`id_detalle`),
  CONSTRAINT `id_compra`
    FOREIGN KEY (`id_compra`)
    REFERENCES `bd_ricco`.`compra` (`id_compra`),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bd_ricco`.`productos` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_producto` ON `bd_ricco`.`detalle` (`id_producto` ASC) VISIBLE;

CREATE INDEX `id_compra` ON `bd_ricco`.`detalle` (`id_compra` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bd_ricco`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_ricco`.`direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(50) NULL DEFAULT NULL,
  `numero` INT NOT NULL,
  `id_barrio` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  CONSTRAINT `_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `bd_ricco`.`usuario` (`id_usuario`),
  CONSTRAINT `id_barrio`
    FOREIGN KEY (`id_barrio`)
    REFERENCES `bd_ricco`.`barrio` (`id_barrio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_barrio` ON `bd_ricco`.`direccion` (`id_barrio` ASC) VISIBLE;

CREATE INDEX `_id_usuario` ON `bd_ricco`.`direccion` (`id_usuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
